# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d1db8e81c4c9c418138a97160c74d72f59c246fa3add0c2aaa9a34c630295e8e9a7bbe31ef6d790629956e159fcffda31bee125b4d22760c07a0683c77cd845

test:
  secret_key_base: 961aa9f48dc46fea51094de0b5eec5929bf93075c478bde20853dd295bce82ed176e0f5be674ae330aac086d8707bf38e29e7b3ad0f61cfbf0eafa6755130c2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
